version: 2.1

orbs:
  android: circleci/android@1.0.3
  sonarcloud: sonarsource/sonarcloud@1.0.2  

jobs:
  setup_and_test:
    docker:
      - image: cimg/node:16.13
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo $CIRCLE_BRANCH
            if [[ $CIRCLE_BRANCH == "node" ]]
            then
              echo 'Setting NX_BASE to last tag'
              echo 'export NX_BASE=`git describe --tags $(git rev-list --tags --max-count=1)`' >> $BASH_ENV
              source $BASH_ENV
            else
              echo 'Setting NX_BASE to origin/node'
              echo 'export NX_BASE="origin/node"' >> $BASH_ENV
              source $BASH_ENV
            fi
            source $BASH_ENV
            echo $NX_BASE
      - persist_to_workspace:
          root: .
          paths:
            - "*"
      - restore_cache:
          name: Restoring npm cache
          keys:
            - node-v2-{{ checksum "package-lock.json" }}-{{ arch }}
            - npm-cache-v1-{{ checksum "package-lock.json" }}-{{ arch }}
      - save_cache:
          name: Caching node modules
          key: node-v2-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - node_modules
      - save_cache:
          name: Caching npm
          key: npm-cache-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - ~/.npm
#      - run:
#          name: Lint commit message
#          command: npx commitlint --from \"origin/node\"
#      - run:
#          name: Type Check
#          command: npm run affected:typecheck -- --base ${NX_BASE}
      - run:
          name: Lint
          command: npm install eslint && npm run-script lint
#      - run:
#          name: Test
#          command: npm run test -- --ci --base ${NX_BASE} --maxWorkers 2 --reporters=default --reporters=jest-junit
#          environment:
#            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - run:
          name: Test
          command: sudo npm install -g @nrwl/cli && export PATH=/usr/local/share/npm/bin:$PATH && nx run-many --target=test --parallel
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
 #     - sonarcloud/scan
      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  sample:
    jobs:
      - setup_and_test
