version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test-android:
    environment:
    machine:
      image: android:202102-01

    steps:
      - checkout

      - run: mkdir /home/circleci/project/junit
      - run:
          name: Node 14 Repo
          command: 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -'
      - run:
          name: Install Node
          command: 'sudo apt-get install -y nodejs'
      - run:
          name: Install Yarn
          command: 'sudo npm install -g yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: chmod +x /home/circleci/project/node_modules/@react-native-community/cli/build/tools/yarn.js
      - run:
          name: Create Build
          command: yarn test:build:android
      - android/accept-licenses
      - android/create-avd:
          avd-name: emulator-5554
          install: true
          system-image: system-images;android-29;default;x86_64
      - android/start-emulator:
          avd-name: emulator-5554
          post-emulator-launch-assemble-command: ''
#      - run: 
#          name: Run Tests
#          command: yarn test:android
#      - android/save-gradle-cache:
#          cache-prefix: v1a
workflows:
  sample:
    jobs:
      - build-and-test-android
