version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test-android:
    parallelism: 5
    executor:
      name: android/android-machine

    steps:
      - checkout

      - run: mkdir /home/circleci/project/junit

      - run:
          name: Node 14 Repo
          command: 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -'

      - run:
          name: Install Node
          command: 'sudo apt-get install -y nodejs'

      - run:
          name: Install Yarn
          command: 'sudo npm install -g yarn'

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run: yarn add --dev jest-junit

      - run:
          name: Create Build
          command: yarn test:build:android

      - android/accept-licenses

      - android/create-avd:
          avd-name: emulator-5554
          install: true
          system-image: system-images;android-29;default;x86_64

      - android/start-emulator:
          avd-name: emulator-5554
          post-emulator-launch-assemble-command: ''

      - run:
          name: Split tests
          command: |
            export TEST=$(circleci tests glob "/home/circleci/project/__tests__/*.js" | circleci tests split)
            echo $TEST
            yarn test $TEST

 #     - android/run-tests:
 #         test-command: yarn test $TEST

      - run:
          command: cp /home/circleci/project/junit.xml /home/circleci/project/junit/junit.xml
          when: always

      - store_test_results:
          path: /home/circleci/project/junit
      - store_artifacts:
          path: /home/circleci/project/junit


workflows:
  sample:
    jobs:
      - build-and-test-android
